### ISSUE TITLE
Online Update Check

### ISSUE THREAD

**Issue by peperonikiller** [B2DevUK/B2_WeatherEssentials#3]
The online version check feature appears to have a bug, it looks like it's displaying the current version as 1.1.1 but displaying the latest version as v1.1.1  Not sure if it's just superficial but thought I'd post it. 
![Screenshot 2024-10-04 174442](https://github.com/user-attachments/assets/0e3de1dd-1d6e-42a8-9567-3b441eca217e)

**Comment by B2DevUK** [comment]
Fixed as of V1.3.0
